### ISSUE TITLE
stop传入fileID暂停后，upload(fileId) 不起作用

### ISSUE THREAD

**Issue by retamia** [fex-team/webuploader#1721]
`$.each( me.pool, function( _, v ) {
    // 只 abort 指定的文件。
    if (v.file !== file) {
        return;
    }
    v.transport && v.transport.abort();
    me._putback(v);
    me._popBlock(v);
});`
stopUpload的时候将该文件的blocks从pool里面移除了

`$.each( me.pool, function( _, v ) {
     // 之前暂停过。
     if (v.file !== file) {
          return;
     }
     v.transport && v.transport.send();
 });
 file.setStatus( Status.QUEUED );
`
starUpload传入file或fileId时候又去pool里面找该文件的block，这不是明显找不到的吗？

**Comment by kevin123de** [comment]
楼主有解决吗！遇到同样的问题

**Comment by coolyal** [comment]
楼主有解决吗！遇到同样的问题

**Comment by retamia** [comment]
最后改用了cancelFile这个接口  然后重新上传的时候调用start    因为已经做了断点续传所以用户体验是差不多的

**Comment by coolyal** [comment]
@retamia 这个思路不错，谢谢！

**Comment by cdmin207078** [comment]
![image](https://user-images.githubusercontent.com/1762278/27031168-bc96c8dc-4fa1-11e7-82e5-3a1be3350d0a.png)
上图摘自 官网api 页面 
没有参数的 `stop` 方法，暂停不了现在
`stop(ture)' ok ,

`stop(file)` 报错,
```
Uncaught TypeError: Cannot read property 'file' of undefined
    at http://localhost:60006/Content/webuploader-0.1.5/webuploader.js:3602:30
    at Function.each (http://localhost:60006/Content/AdminLTE/plugins/jQuery/jquery-2.2.3.min.js:2:2861)
    at child.stopUpload (http://localhost:60006/Content/webuploader-0.1.5/webuploader.js:3599:23)
    at child.invoke (http://localhost:60006/Content/webuploader-0.1.5/webuploader.js:1260:47)
    at Uploader.request (http://localhost:60006/Content/webuploader-0.1.5/webuploader.js:1312:34)
    at Uploader.(anonymous function) [as stop] (http://localhost:60006/Content/webuploader-0.1.5/webuploader.js:767:29)
    at HTMLAnchorElement.<anonymous> (http://localhost:60006/js/attachment.js:482:22)
    at HTMLDocument.dispatch (http://localhost:60006/Content/AdminLTE/plugins/jQuery/jquery-2.2.3.min.js:3:7537)
    at HTMLDocument.r.handle (http://localhost:60006/Content/AdminLTE/plugins/jQuery/jquery-2.2.3.min.js:3:5620)
```



我想问，可以开放一个 传入fileId 的stop 方法吗？ 就像 remove & cancel 一样

**Comment by yangxiaofengalex** [comment]
@retamia 如果是多个文件同时上传，其中某个暂停就不行了，开启暂停不是重新上传
